gantt
    title Calenderização
    dateFormat  YYYY-MM-DD
    axisFormat  %b %y

    section 1ª Fase
        Levantamento do Estado da Arte           :a1, 2019-10-01, 2020-01-15
    section 2ª Fase
        Arquitetura e Prototipagem     :a2, 2020-01-01, 2020-05-01
    section 3ª Fase
        Desenvolvimento Final      :a3, 2020-03-01, 2020-07-01
    section 4ª Fase
        Escrita da Dissertação      :a4, 2019-12-01,2020-08-15
