site_name: Musikla
theme: material
markdown_extensions:
  - codehilite
nav:
  - Home: 'index.md'
  - Getting Started: 
    - 'Notes & Rests': 'getting-started/notes-and-rests.md'
    - 'Combinators': 'getting-started/combinators.md'
    - 'Chords': 'getting-started/chords.md'
    - 'Voices': 'getting-started/voices.md'
    - 'Sound Files': 'getting-started/sound-files.md'
    - 'Keyboards': 'getting-started/keyboards.md'
    - 'Grids': 'getting-started/grids.md'
    - 'Programming': 'getting-started/programming.md'
  - Cookbook:
    - 'Keyboard':
      - 'Custom Keyboards': 'cookbook/keyboards/custom-keyboard.md'
      - 'Piano Keyboards': 'cookbook/keyboards/paino-keyboard.md'
      - 'MIDI Keyboards': 'cookbook/keyboards/midi-keyboard.md'
    - 'Recording to Traktion Waveform': 'cookbook/midi-output-waveform.md'
    - 'Multiple Outputs': 'cookbook/multiple-outputs.md'
  - API:
    - std: 'api/std.md'
    - keyboard: 'api/keyboard.md'
    - music: 'api/music.md'